# permissions for end users to edit argocds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: argocd-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: argocd-operator-rewrite
    app.kubernetes.io/part-of: argocd-operator-rewrite
    app.kubernetes.io/managed-by: kustomize
  name: argocd-editor-role
rules:
- apiGroups:
  - argoproj.io
  resources:
  - argocds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - argocds/status
  verbs:
  - get
